#!/usr/bin/env python3
"""Build node with remote execution (reclient + EngFlow), like Chromium.

Compiles run remotely through rewrapper on EngFlow workers running the
toolchain image (Dockerfile next to this script; Ubuntu 22.04's gcc), pinned by
digest. Configure probes, host tool runs (torque, mksnapshot, ...) and links
stay local, so the local toolchain must be the same:

- In CI (backend's linux-node-build, built FROM the toolchain image) and in
  build-in-container.sh, this runs inside the toolchain image itself.
- Run directly on a host (`node build.js`, like Chromium's autoninja), it first
  checks that the host's gcc, g++, binutils and glibc are identical to the
  workers' and stops otherwise; use build-in-container.sh on such hosts.

The build tools come from the Chromium fork's pins (toolchain.json) and its
reclient configs (chromium_cfgs/), both generated by update-toolchain.py:

  .rbe/reclient reclient (rewrapper/reproxy/bootstrap), from CIPD
  .rbe/ninja    ninja, from CIPD

Compile command lines only use paths relative to the checkout (rewrapper's
exec_root), so every checkout location produces the same remote cache keys.

Usage (from build.js, after the driver source is generated):
  python3 replay_build_scripts/rbe/build-rbe.py [-j N]

EngFlow access: the EngFlow client cert/key files (Secrets Manager
engflow-certificate / engflow-key) in ENGFLOW_CERT_FILE / ENGFLOW_KEY_FILE, or
the RBE_* environment Chromium's builds use (RBE_tls_client_auth_cert, ...).
"""

import argparse
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.request
import zipfile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
TC = os.path.join(ROOT, ".rbe")
OUT = os.path.join(ROOT, "out")
BUILD_DIR = os.path.join(OUT, "Release")
TOOLCHAIN_STAMP = os.path.join(BUILD_DIR, ".toolchain")

with open(os.path.join(SCRIPT_DIR, "toolchain.json")) as f:
  PINS = json.load(f)


def log(msg):
  print(f"[build-rbe] {msg}", flush=True)


def fetch(url):
  log(f"downloading {url}")
  with urllib.request.urlopen(url) as resp:
    return resp.read()


def install(name, pin_key, extract):
  """Install a toolchain component into .rbe/<name> unless the pin matches."""
  dest = os.path.join(TC, name)
  stamp = os.path.join(TC, f"{name}.stamp")
  want = json.dumps(PINS[pin_key], sort_keys=True)
  if os.path.exists(stamp) and open(stamp).read() == want:
    return
  shutil.rmtree(dest, ignore_errors=True)
  os.makedirs(dest)
  extract(dest)
  with open(stamp, "w") as f:
    f.write(want)


def extract_cipd(package, version):
  def run(dest):
    url = f"https://chrome-infra-packages.appspot.com/dl/{package}/+/{version}"
    with zipfile.ZipFile(io.BytesIO(fetch(url))) as z:
      for info in z.infolist():
        z.extract(info, dest)
        mode = info.external_attr >> 16
        if mode:
          os.chmod(os.path.join(dest, info.filename), mode & 0o777)
  return run


def in_toolchain_image():
  """True inside the toolchain image (or one built FROM it), False on a host."""
  try:
    have = open("/etc/node-rbe-toolchain").read().strip()
  except FileNotFoundError:
    return False
  with open(os.path.join(SCRIPT_DIR, "Dockerfile"), "rb") as f:
    want = hashlib.sha256(f.read()).hexdigest()[:16]
  if have != want:
    sys.exit(f"[build-rbe] this container has toolchain image {have}, but the checkout's "
             f"Dockerfile is {want}; rebuild/pull the image")
  return True


def worker_image():
  """The toolchain image's digest ref, which the remote workers run."""
  image = os.environ.get("REPLAY_RBE_CONTAINER_IMAGE", "")
  if not image:
    image = subprocess.check_output([os.path.join(SCRIPT_DIR, "toolchain-image.sh"), "digest"],
                                    text=True).strip()
  if "@sha256:" not in image:
    sys.exit(f"[build-rbe] expected a digest ref for the toolchain image, got {image!r}")
  return image


# What the local steps (configure probes, links, host tools) depend on.
TOOLCHAIN_PROBE = "export LC_ALL=C; gcc --version | head -1; g++ --version | head -1; ld --version | head -1; ldd --version | head -1"


def check_host_toolchain(env):
  """On a host, local steps use the host's toolchain: it must be the workers'."""
  local = subprocess.run(["sh", "-c", TOOLCHAIN_PROBE], cwd=ROOT, env=env,
                         capture_output=True, text=True).stdout
  # A cheap remote action on the worker image (cached after the first run).
  remote = subprocess.run(
      [os.path.join(TC, "reclient", "rewrapper"), f"-cfg={os.path.join(TC, 'rewrapper_linux.cfg')}",
       f"-exec_root={ROOT}", "-labels=type=tool", "-exec_strategy=remote", "-inputs=build.js",
       "/bin/sh", "-c", TOOLCHAIN_PROBE],
      cwd=ROOT, env=env, capture_output=True, text=True)
  if remote.returncode != 0:
    sys.exit(f"[build-rbe] couldn't run the toolchain check on EngFlow:\n{remote.stdout}{remote.stderr}")
  if local != remote.stdout:
    sys.exit("[build-rbe] this host's toolchain differs from the RBE workers' (toolchain image):\n"
             f"--- host\n{local}--- workers\n{remote.stdout}"
             "Local and remote build steps would use different compilers. Build in the toolchain "
             "image instead: replay_build_scripts/rbe/build-in-container.sh")
  log("host toolchain matches the RBE workers'")


def setup_toolchain():
  os.makedirs(TC, exist_ok=True)
  install("reclient", "reclient", extract_cipd("infra/rbe/client/linux-amd64", PINS["reclient"]))
  install("ninja", "ninja", extract_cipd("infra/3pp/tools/ninja/linux-amd64", PINS["ninja"]))

  # configure and gyp bake CC/CXX into build.ninja; point them at the wrapper.
  bin_dir = os.path.join(TC, "bin")
  os.makedirs(bin_dir, exist_ok=True)
  for tool in ("gcc", "g++"):
    path = os.path.join(bin_dir, tool)
    with open(path, "w") as f:
      f.write(f'#!/bin/sh\nexec "{SCRIPT_DIR}/cc-wrapper.sh" {tool} "$@"\n')
    os.chmod(path, 0o755)


def socket_address():
  # unix socket paths are length-limited; key on the checkout so concurrent
  # builds in different checkouts (and Chromium's reproxy) don't collide.
  digest = hashlib.sha256(ROOT.encode()).hexdigest()[:16]
  return f"unix:///tmp/reproxy-node-{digest}.sock"


def write_cfgs(image):
  """Chromium's reclient configs (see update-toolchain.py) with our specifics.

  The socket is passed through RBE_server_address instead (rbe_env), so it is
  dropped here; the scandeps path points at our reclient download, and remote
  workers run our toolchain image instead of Chromium's.
  """
  overrides = {
      "reproxy.cfg": {"depsscanner_address": f"exec://{os.path.join(TC, 'reclient', 'scandeps_server')}"},
      "rewrapper_linux.cfg": {"platform": f"container-image=docker://{image},OSFamily=linux"},
  }
  for name, extra in overrides.items():
    with open(os.path.join(SCRIPT_DIR, "chromium_cfgs", name)) as f:
      lines = [l for l in f.read().splitlines()
               if l.split("=", 1)[0] not in ("server_address", *extra)]
    lines += [f"{k}={v}" for k, v in extra.items()]
    with open(os.path.join(TC, name), "w") as f:
      f.write("\n".join(lines) + "\n")


def rbe_env():
  logs = os.path.join(BUILD_DIR, ".reproxy_tmp", "logs")
  cache = os.path.join(BUILD_DIR, ".reproxy_tmp", "cache")
  # Only this run's logs: out/Release persists across CI jobs, which upload them.
  shutil.rmtree(logs, ignore_errors=True)
  os.makedirs(logs, exist_ok=True)
  os.makedirs(cache, exist_ok=True)
  env = dict(os.environ)
  # EngFlow, as for Chromium; the client cert/key come from the environment.
  env.setdefault("RBE_service", "simpsonite.cluster.engflow.com:443")
  env.setdefault("RBE_service_no_auth", "true")
  env.setdefault("RBE_use_application_default_credentials", "true")
  for var, file_var in (("RBE_tls_client_auth_cert", "ENGFLOW_CERT_FILE"),
                        ("RBE_tls_client_auth_key", "ENGFLOW_KEY_FILE")):
    if os.environ.get(file_var):
      env[var] = os.path.abspath(os.environ[file_var])
    if not os.path.isfile(env.get(var, "")):
      sys.exit(f"[build-rbe] set {file_var} to the EngFlow client "
               f"{'certificate' if 'cert' in var else 'key'} file (or {var})")
  env.update({
      "RBE_server_address": socket_address(),
      "RBE_output_dir": logs,
      "RBE_proxy_log_dir": logs,
      "RBE_log_dir": logs,
      "RBE_cache_dir": cache,
      # Never race against local compiles: keep local cores free and only fall
      # back when remote execution fails.
      "RBE_exec_strategy": "remote_local_fallback",
      "REPLAY_RBE_REPROXY": "1",
  })
  if os.environ.get("REPLAY_RBE_REQUIRE_REMOTE") == "1":
    # Chromium's fail-early threshold (4000 actions) exceeds node's ~3300
    # compiles: with remote execution broken (bad cert, unpullable worker
    # image) give up after a few hundred fallbacks instead of compiling
    # everything locally first.
    env["RBE_fail_early_min_action_count"] = "200"
  return env


def prepare_out_dir(toolchain):
  """Clear outputs that ninja would wrongly consider up to date."""
  # A make build from before the switch to RBE (cached CI checkouts).
  if os.path.exists(os.path.join(OUT, "Makefile")):
    log("removing the make build in out/")
    os.remove(os.path.join(OUT, "Makefile"))
    shutil.rmtree(BUILD_DIR, ignore_errors=True)
  # ninja reruns a command when the command changes, not when the compiler
  # behind it does: start over whenever the toolchain image (digest) changes.
  try:
    built_with = open(TOOLCHAIN_STAMP).read().strip()
  except FileNotFoundError:
    built_with = None
  if os.path.isdir(BUILD_DIR) and built_with != toolchain:
    log(f"toolchain changed ({built_with} -> {toolchain}); rebuilding out/Release from scratch")
    shutil.rmtree(BUILD_DIR)
  os.makedirs(BUILD_DIR, exist_ok=True)
  with open(TOOLCHAIN_STAMP, "w") as f:
    f.write(toolchain)


CONFIGURE_STAMP = os.path.join(BUILD_DIR, ".configure")


def configure_inputs(env):
  """Hash of what configure reads: rerunning it rewrites config.gypi, which
  makes ninja regenerate ICU data and the JS bundle and relink, so skip it when
  nothing changed."""
  files = subprocess.check_output(
      ["git", "ls-files", "-z", "--", "configure", "configure.py", "*.gyp", "*.gypi",
       "tools/gyp", "tools/v8_gypfiles", "tools/icu"], cwd=ROOT).split(b"\0")
  h = hashlib.sha256()
  h.update(f"{env['CC']}\0{env['CXX']}\0{sys.version}\0".encode())
  for name in sorted(f for f in files if f):
    h.update(name + b"\0")
    try:
      with open(os.path.join(ROOT, name.decode()), "rb") as f:
        h.update(hashlib.sha256(f.read()).digest())
    except FileNotFoundError:
      h.update(b"missing")
  return h.hexdigest()


def configure():
  env = dict(os.environ)
  env["CC"] = os.path.join(TC, "bin", "gcc")
  env["CXX"] = os.path.join(TC, "bin", "g++")
  env.pop("REPLAY_RBE_REPROXY", None)
  inputs = configure_inputs(env)
  try:
    done = open(CONFIGURE_STAMP).read() == inputs
  except FileNotFoundError:
    done = False
  if done and os.path.exists(os.path.join(BUILD_DIR, "build.ninja")):
    log("configure inputs unchanged; not reconfiguring")
    return
  subprocess.check_call([sys.executable, "configure.py", "--ninja"], cwd=ROOT, env=env)
  with open(CONFIGURE_STAMP, "w") as f:
    f.write(inputs)


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("-j", type=int, default=200, help="ninja parallelism (mostly remote)")
  args = parser.parse_args()

  in_image = in_toolchain_image()
  image = worker_image()
  prepare_out_dir(image)
  setup_toolchain()
  write_cfgs(image)

  reclient = os.path.join(TC, "reclient")
  cfg = os.path.join(TC, "reproxy.cfg")
  env = rbe_env()
  # A stale reproxy from an interrupted build would hold the socket.
  subprocess.call([os.path.join(reclient, "bootstrap"), "--shutdown", f"--cfg={cfg}"], env=env,
                  stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  subprocess.check_call([os.path.join(reclient, "bootstrap"),
                         f"--re_proxy={os.path.join(reclient, 'reproxy')}", f"--cfg={cfg}"], env=env)
  start = time.time()
  stats = ""
  rv = 1
  try:
    if not in_image:
      check_host_toolchain(env)
    configure()
    start = time.time()
    rv = subprocess.call([os.path.join(TC, "ninja", "ninja"), "-C", BUILD_DIR, f"-j{args.j}"],
                         cwd=ROOT, env={**env, "RECORD_REPLAY_DONT_RECORD": "1"})
  finally:
    # Prints the remote/cache-hit/fallback summary.
    shutdown = subprocess.run([os.path.join(reclient, "bootstrap"), "--shutdown", f"--cfg={cfg}"],
                              env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    stats = shutdown.stdout
    print(stats, end="", flush=True)
  log(f"ninja finished in {time.time() - start:.0f}s with exit code {rv}")
  # A worker image EngFlow can't pull (or any other remote failure) silently
  # degrades into local compiles; CI sets this so that fails loudly instead.
  fallbacks = re.search(r"(\d+) local fallbacks?", stats)
  if rv == 0 and fallbacks and os.environ.get("REPLAY_RBE_REQUIRE_REMOTE") == "1":
    log(f"{fallbacks.group(1)} compiles fell back to local execution; "
        f"see out/Release/.reproxy_tmp/logs (reproxy.INFO, *.rrpl) for why")
    rv = 1
  sys.exit(rv)


if __name__ == "__main__":
  main()
