#!/usr/bin/env python3
"""Build node with remote execution (reclient + EngFlow), like Chromium.

Compiles run remotely through rewrapper; configure probes, host tool runs
(torque, mksnapshot, ...) and links stay local. This runs inside an image built
FROM the toolchain image (Dockerfile next to this script; Ubuntu 22.04's gcc)
and the remote workers run that same image, pinned by digest
(REPLAY_RBE_CONTAINER_IMAGE, from `toolchain-image.sh pull`), so local and
remote compiles see identical gcc, headers and libraries.

The build tools come from the Chromium fork's pins (toolchain.json) and its
reclient configs (chromium_cfgs/), both generated by update-toolchain.py:

  .rbe/reclient reclient (rewrapper/reproxy/bootstrap), from CIPD
  .rbe/ninja    ninja, from CIPD

Compile command lines only use paths relative to the checkout (rewrapper's
exec_root), so every checkout location produces the same remote cache keys.

In CI this runs in backend's linux-node-build image, which is built FROM the
toolchain image and sets REPLAY_RBE_CONTAINER_IMAGE to its digest.

Usage (from build.js, after the driver source is generated):
  python3 replay_build_scripts/rbe/build-rbe.py [-j N]

Needs the same RBE_* environment Chromium's CI uses (RBE_service,
RBE_tls_client_auth_cert, RBE_tls_client_auth_key, ...).
"""

import argparse
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.request
import zipfile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
TC = os.path.join(ROOT, ".rbe")
OUT = os.path.join(ROOT, "out")
BUILD_DIR = os.path.join(OUT, "Release")
TOOLCHAIN_STAMP = os.path.join(BUILD_DIR, ".toolchain")

with open(os.path.join(SCRIPT_DIR, "toolchain.json")) as f:
  PINS = json.load(f)


def log(msg):
  print(f"[build-rbe] {msg}", flush=True)


def fetch(url):
  log(f"downloading {url}")
  with urllib.request.urlopen(url) as resp:
    return resp.read()


def install(name, pin_key, extract):
  """Install a toolchain component into .rbe/<name> unless the pin matches."""
  dest = os.path.join(TC, name)
  stamp = os.path.join(TC, f"{name}.stamp")
  want = json.dumps(PINS[pin_key], sort_keys=True)
  if os.path.exists(stamp) and open(stamp).read() == want:
    return
  shutil.rmtree(dest, ignore_errors=True)
  os.makedirs(dest)
  extract(dest)
  with open(stamp, "w") as f:
    f.write(want)


def extract_cipd(package, version):
  def run(dest):
    url = f"https://chrome-infra-packages.appspot.com/dl/{package}/+/{version}"
    with zipfile.ZipFile(io.BytesIO(fetch(url))) as z:
      for info in z.infolist():
        z.extract(info, dest)
        mode = info.external_attr >> 16
        if mode:
          os.chmod(os.path.join(dest, info.filename), mode & 0o777)
  return run


def check_toolchain_image():
  """Local compiles must use exactly the gcc the remote workers use."""
  with open(os.path.join(SCRIPT_DIR, "Dockerfile"), "rb") as f:
    want = hashlib.sha256(f.read()).hexdigest()[:16]
  try:
    have = open("/etc/node-rbe-toolchain").read().strip()
  except FileNotFoundError:
    have = None
  if have != want:
    sys.exit(f"[build-rbe] must run inside the toolchain image for this Dockerfile "
             f"(tag {want}, found {have}); see toolchain-image.sh")
  image = os.environ.get("REPLAY_RBE_CONTAINER_IMAGE", "")
  if "@sha256:" not in image:
    sys.exit("[build-rbe] REPLAY_RBE_CONTAINER_IMAGE must be the toolchain image's digest ref "
             "(`toolchain-image.sh pull`)")
  return image


def setup_toolchain():
  os.makedirs(TC, exist_ok=True)
  install("reclient", "reclient", extract_cipd("infra/rbe/client/linux-amd64", PINS["reclient"]))
  install("ninja", "ninja", extract_cipd("infra/3pp/tools/ninja/linux-amd64", PINS["ninja"]))

  # configure and gyp bake CC/CXX into build.ninja; point them at the wrapper.
  bin_dir = os.path.join(TC, "bin")
  os.makedirs(bin_dir, exist_ok=True)
  for tool in ("gcc", "g++"):
    path = os.path.join(bin_dir, tool)
    with open(path, "w") as f:
      f.write(f'#!/bin/sh\nexec "{SCRIPT_DIR}/cc-wrapper.sh" {tool} "$@"\n')
    os.chmod(path, 0o755)


def socket_address():
  # unix socket paths are length-limited; key on the checkout so concurrent
  # builds in different checkouts (and Chromium's reproxy) don't collide.
  digest = hashlib.sha256(ROOT.encode()).hexdigest()[:16]
  return f"unix:///tmp/reproxy-node-{digest}.sock"


def write_cfgs(image):
  """Chromium's reclient configs (see update-toolchain.py) with our specifics.

  The socket is passed through RBE_server_address instead (rbe_env), so it is
  dropped here; the scandeps path points at our reclient download, and remote
  workers run our toolchain image instead of Chromium's.
  """
  overrides = {
      "reproxy.cfg": {"depsscanner_address": f"exec://{os.path.join(TC, 'reclient', 'scandeps_server')}"},
      "rewrapper_linux.cfg": {"platform": f"container-image=docker://{image},OSFamily=linux"},
  }
  for name, extra in overrides.items():
    with open(os.path.join(SCRIPT_DIR, "chromium_cfgs", name)) as f:
      lines = [l for l in f.read().splitlines()
               if l.split("=", 1)[0] not in ("server_address", *extra)]
    lines += [f"{k}={v}" for k, v in extra.items()]
    with open(os.path.join(TC, name), "w") as f:
      f.write("\n".join(lines) + "\n")


def rbe_env():
  logs = os.path.join(BUILD_DIR, ".reproxy_tmp", "logs")
  cache = os.path.join(BUILD_DIR, ".reproxy_tmp", "cache")
  # Only this run's logs: out/Release persists across CI jobs, which upload them.
  shutil.rmtree(logs, ignore_errors=True)
  os.makedirs(logs, exist_ok=True)
  os.makedirs(cache, exist_ok=True)
  env = dict(os.environ)
  env.update({
      "RBE_server_address": socket_address(),
      "RBE_output_dir": logs,
      "RBE_proxy_log_dir": logs,
      "RBE_log_dir": logs,
      "RBE_cache_dir": cache,
      # Never race against local compiles: keep local cores free and only fall
      # back when remote execution fails.
      "RBE_exec_strategy": "remote_local_fallback",
      "REPLAY_RBE_REPROXY": "1",
  })
  if os.environ.get("REPLAY_RBE_REQUIRE_REMOTE") == "1":
    # Chromium's fail-early threshold (4000 actions) exceeds node's ~3300
    # compiles: with remote execution broken (bad cert, unpullable worker
    # image) give up after a few hundred fallbacks instead of compiling
    # everything locally first.
    env["RBE_fail_early_min_action_count"] = "200"
  return env


def prepare_out_dir(toolchain):
  """Clear outputs that ninja would wrongly consider up to date."""
  # A make build from before the switch to RBE (cached CI checkouts).
  if os.path.exists(os.path.join(OUT, "Makefile")):
    log("removing the make build in out/")
    os.remove(os.path.join(OUT, "Makefile"))
    shutil.rmtree(BUILD_DIR, ignore_errors=True)
  # ninja reruns a command when the command changes, not when the compiler
  # behind it does: start over whenever the toolchain image (digest) changes.
  try:
    built_with = open(TOOLCHAIN_STAMP).read().strip()
  except FileNotFoundError:
    built_with = None
  if os.path.isdir(BUILD_DIR) and built_with != toolchain:
    log(f"toolchain changed ({built_with} -> {toolchain}); rebuilding out/Release from scratch")
    shutil.rmtree(BUILD_DIR)
  os.makedirs(BUILD_DIR, exist_ok=True)
  with open(TOOLCHAIN_STAMP, "w") as f:
    f.write(toolchain)


def configure():
  # Cheap, and ninja only reruns commands whose command line changed, so
  # always regenerating keeps build.ninja in sync with the .gyp files.
  env = dict(os.environ)
  env["CC"] = os.path.join(TC, "bin", "gcc")
  env["CXX"] = os.path.join(TC, "bin", "g++")
  env.pop("REPLAY_RBE_REPROXY", None)
  subprocess.check_call([sys.executable, "configure.py", "--ninja"], cwd=ROOT, env=env)


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("-j", type=int, default=200, help="ninja parallelism (mostly remote)")
  args = parser.parse_args()

  image = check_toolchain_image()
  prepare_out_dir(image)
  setup_toolchain()
  write_cfgs(image)
  configure()

  reclient = os.path.join(TC, "reclient")
  cfg = os.path.join(TC, "reproxy.cfg")
  env = rbe_env()
  # A stale reproxy from an interrupted build would hold the socket.
  subprocess.call([os.path.join(reclient, "bootstrap"), "--shutdown", f"--cfg={cfg}"], env=env,
                  stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  subprocess.check_call([os.path.join(reclient, "bootstrap"),
                         f"--re_proxy={os.path.join(reclient, 'reproxy')}", f"--cfg={cfg}"], env=env)
  start = time.time()
  stats = ""
  try:
    rv = subprocess.call([os.path.join(TC, "ninja", "ninja"), "-C", BUILD_DIR, f"-j{args.j}"],
                         cwd=ROOT, env={**env, "RECORD_REPLAY_DONT_RECORD": "1"})
  finally:
    # Prints the remote/cache-hit/fallback summary.
    shutdown = subprocess.run([os.path.join(reclient, "bootstrap"), "--shutdown", f"--cfg={cfg}"],
                              env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    stats = shutdown.stdout
    print(stats, end="", flush=True)
  log(f"ninja finished in {time.time() - start:.0f}s with exit code {rv}")
  # A worker image EngFlow can't pull (or any other remote failure) silently
  # degrades into local compiles; CI sets this so that fails loudly instead.
  fallbacks = re.search(r"(\d+) local fallbacks?", stats)
  if rv == 0 and fallbacks and os.environ.get("REPLAY_RBE_REQUIRE_REMOTE") == "1":
    log(f"{fallbacks.group(1)} compiles fell back to local execution; "
        f"see out/Release/.reproxy_tmp/logs (reproxy.INFO, *.rrpl) for why")
    rv = 1
  sys.exit(rv)


if __name__ == "__main__":
  main()
