// PLACEHOLDER — compile/link validation only.
//
// The real src/node_record_replay_driver.cc is GENERATED by the Replay build
// flow (build.js): it octal-escapes the downloaded recordreplay driver binary
// into gRecordReplayDriver, sets gRecordReplayDriverSize, and computes
// gBuildId. That generated file is .gitignored.
//
// node's standard CI (the GitHub Actions coverage/shared-library matrix) does
// NOT run the Replay driver-generation step, so without this file the
// libnode_base.a archive fails on a missing object and the port can't be
// compile-validated. This committed placeholder defines the symbols node.cc
// references (see node.cc gRecordReplayDriver / gRecordReplayDriverSize /
// gBuildId) with empty values so the build links; at runtime
// InitializeRecordReplay sees a zero-length driver and simply records nothing.
//
// The real build flow overwrites this file with the embedded driver, so
// functional record/replay builds are unaffected.
namespace node {
char gRecordReplayDriver[] = "";
int gRecordReplayDriverSize = 0;
char gBuildId[] = "";
}  // namespace node
