name: Build/Test
on:
  workflow_dispatch:
    inputs:
      clobber:
        description: "Build node from scratch"
        type: boolean
        required: false
  push:
    branches:
      - master

jobs:
  build-test:
    name: Trigger build/test run
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@e870a1112fcc1faeeeeea3c1b0ce544e5ad01844
        with:
          authkey: ${{ secrets.TAILSCALE_API_KEY }}
          version: "1.28.0"
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-test
        env:
          BUILD_TEST_AUTHORIZATION: ${{ secrets.BUILD_TEST_AUTHORIZATION }}
          BUILD_TEST_HOSTNAME: a49855c191a944333918aea7ad31bc76-6a8a830d89921d8a.elb.us-east-2.amazonaws.com
          BUILD_TEST_PORT: ${{ secrets.BUILD_TEST_PORT }}
          BUILD_TEST_INSECURE: ${{ secrets.BUILD_TEST_INSECURE }}
          INPUT_CLOBBER: ${{ github.event.inputs.clobber }}
